# Generated by Django 4.0.3 on 2022-03-23 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_couple', to=settings.AUTH_USER_MODEL, verbose_name='Пара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matcher', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user', 'matching'), name='unique_follow'),
        ),
    ]
